spring:
  application:
    name: email-service
  mail:
    host: smtp.gmail.com
    port: 587
    username: cartcommunityltd@gmail.com
    password: rudccmucwisboacc
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
server:
  port: 8084
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
management:
  tracing:
    sampling:
      probability: 0.1