spring:
  application:
    name: product-service
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/productdbtest
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
#  config:
server:
  port: 8082
#    import: "optional:configserver:http://localhost:8088"
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
management:
  tracing:
    sampling:
      probability: 0.1
